function buildings = PPP_buildings(lambda, Lmax, R)
% Returns a matrix of buildings defined by extreme points of lines:
% builidings = [
%				x0_A, y0_A, x0_B, y0_B;
%				x1_A, y1_A, x1_B, y1_B;
%				... ]


centers = PPP_disk(lambda, R); %centers of the buildings generated by a PPP.

N_buildings = size(centers, 1);  % Number of buildings generated

% Random Building shapes
lengths = Lmax * rand(N_buildings, 1);  % l ~ U(0, Lmax)
angle = pi * rand(N_buildings, 1);      % angle ~ U(0, pi)

% If fixed pdf
% lengths = Lmax/2 * ones(N_buildings, 1);  % l ~ U(0, Lmax)
% angle = 0 * ones(N_buildings, 1);      % angle ~ U(0, pi)

buildings = [-lengths/2 .* cos(angle), -lengths/2 .* sin(angle), ...
             +lengths/2 .* cos(angle), +lengths/2 .* sin(angle)];

buildings = buildings + [centers, centers];

end
